services:
  api-gateway:
    image: victor.fisyuk/messaging-microservices-demo/api-gateway:0.0.1-SNAPSHOT
    container_name: api-gateway
    ports:
      - "8080:8080"

  messages-service:
    image: victor.fisyuk/messaging-microservices-demo/messages-service:0.0.1-SNAPSHOT
    container_name: messages-service

  profiles-service:
    image: victor.fisyuk/messaging-microservices-demo/profiles-service:0.0.1-SNAPSHOT
    container_name: profiles-service

networks:
  default:
    external:
      name: messaging-microservices-demo
