# Provisions the following containers:
#   - PostgreSQL 14.2
#   - Keycloak 14.0.0
#   - Consul 1.11.4

services:
  postgres:
    image: postgres:14.2
    container_name: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
    volumes:
      - postgres-data:/var/lib/postgresql/data

  keycloak:
    image: jboss/keycloak:14.0.0
    container_name: keycloak
    restart: always
    ports:
      - '8180:8080'
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=secret
      - DB_ADDR=postgres
      - DB_PORT=5432
      - DB_DATABASE=keycloak
      - DB_USER=postgres
      - DB_PASSWORD=secret
      - KEYCLOAK_FRONTEND_URL=http://localhost:8180/auth/
    depends_on:
      - postgres

  consul:
    image: consul:1.11.4
    container_name: consul
    restart: always
    ports:
      - '8500:8500'
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    volumes:
      - consul-data:/consul/data

volumes:
  postgres-data:
    name: postgres-data
  consul-data:
    name: consul-data

networks:
  default:
    name: messaging-microservices-demo
