# Provisions the following containers:
#   - PostgreSQL 14.2
#   - Keycloak 14.0.0

services:
  postgres:
    image: postgres:14.2
    container_name: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
    volumes:
      - postgres-data:/var/lib/postgresql/data

  keycloak:
    image: jboss/keycloak:14.0.0
    container_name: keycloak
    restart: always
    ports:
      - '8180:8080'
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=secret
      - DB_ADDR=postgres
      - DB_PORT=5432
      - DB_DATABASE=keycloak
      - DB_USER=postgres
      - DB_PASSWORD=secret
    depends_on:
      - postgres

volumes:
  postgres-data:
    name: postgres-data

networks:
  default:
    name: messaging-microservices-demo
